name: Build APK with Pre-built Action

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the APK
        uses: anacrolix/kivy-buildozer-action@v1
        id: buildozer
        with:
          build_dir: .buildozer

      - name: Upload the APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: ${{ steps.buildozer.outputs.apk_file }}
