name: Build APK With Verified Action (Corrected)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer (Verified Action)
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          # This specifies the command to run.
          # The action will automatically find the buildozer.spec file.
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          # This path comes from the output of the build action.
          path: ${{ steps.buildozer.outputs.apk_path }}
